package com.dino.domain.events;

public interface EventNames {
    String PLAYER_JOINED = "PLAYER_JOINED";
    String PLAYER_READY = "PLAYER_READY";
    String GAME_STARTED = "GAME_STARTED";
    String SNAPSHOT_RECEIVED = "SNAPSHOT_RECEIVED";
    String BUTTON_STATE_CHANGED = "BUTTON_STATE_CHANGED";
    String PLAYER_DIED = "PLAYER_DIED";
    String PLAYER_REACHED_EXIT = "PLAYER_REACHED_EXIT";
    String SCORE_CHANGED = "SCORE_CHANGED";
    String ROOM_RESET = "ROOM_RESET";
    String LEVEL_COMPLETED = "LEVEL_COMPLETED";
    String GAME_OVER = "GAME_OVER";
    String PLAYER_DISCONNECTED = "PLAYER_DISCONNECTED";
}
